"""Dev-time generator for country_codes_data.py.

The country list is nearly static, so we PRECOMPUTE it once (offline) instead of
fetching from the World Bank API on every cold start. Run this occasionally
(e.g. once every few months) to refresh the bundled data:

    cd backend && python scripts/generate_country_codes.py

Requires `pycountry` (a dev-only dependency — NOT in requirements.txt, so it never
ships to Vercel). pycountry's ISO-3166 alpha-3 codes match World Bank country codes
for sovereign states.
"""
import json
import os

import pycountry


def build_index() -> dict:
    idx = {}
    for c in pycountry.countries:
        iso3 = c.alpha_3
        for key in (
            c.name,
            getattr(c, "common_name", None),
            getattr(c, "official_name", None),
            c.alpha_2,
            c.alpha_3,
        ):
            if key:
                idx[key.lower()] = iso3
    return dict(sorted(idx.items()))


HEADER = '''"""AUTO-GENERATED by scripts/generate_country_codes.py from pycountry (ISO-3166).
Do NOT edit by hand — re-run the generator instead.
Maps a lower-cased country name / ISO-2 / ISO-3 -> World Bank ISO-3 code.
"""
COUNTRY_INDEX = '''


if __name__ == "__main__":
    idx = build_index()
    out = os.path.join(os.path.dirname(__file__), "..", "country_codes_data.py")
    with open(out, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write(json.dumps(idx, indent=0, ensure_ascii=True))
        f.write("\n")
    print(f"wrote {len(idx)} lookup keys for {len(set(idx.values()))} countries -> {os.path.abspath(out)}")
